#!/usr/bin/python3
import sys


def factorize():
    try:
        file = sys.argv[1]
        with open(file) as f:
            for line in f:
                line = int(line)
                i = 2
                while i < line:
                    if (line % i) == 0:
                        print("{}={}*{}".format(line, line//i, i))
                        break
                    i += 1

    except (IndexError):
        pass


factorize()
